name: Fix Code Style
 
on:
  workflow_call:
 
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist
        working-directory: ./src

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: ./src

      - name: Run tests
        run: php artisan test 
        working-directory: ./src